### ISSUE TITLE
v144.3 Jitpack no longer exists.

### ISSUE THREAD

**Issue by MEEPofFaith** [GlennFolker/EntityAnno#1]
Needs to be updated to v145.
![2023_08_01_08_41_23_notepad++](https://github.com/GlennFolker/EntityAnno/assets/54301439/a60262f1-aa9c-42fd-8f33-cfa1b94730b4)
![2023_08_01_08_39_39_cmd](https://github.com/GlennFolker/EntityAnno/assets/54301439/fa072197-f20d-4211-9cf3-d91d296a170e)

**Comment by Anuken** [comment]
~~surely there must be a way to specify version externally~~

**Comment by GglLfr** [comment]
> ~surely there must be a way to specify version externally~

None that I'm aware of; how about [this](https://github.com/Anuken/MindustryJavaModTemplate/blob/6b99e92809c8e74a9b25c9236a5f6d540c40ae28/build.gradle#L36-L43) snippet? Seems like it could be adapted into overriding the dependency for the `:entity` module itself.

**Comment by GlennFolker** [comment]
[This PR](#2) fixes this (right?)
